runtime: python
env: flex
entrypoint: gunicorn -p $PORT main:app

runtime_config:
  python_version: 3.7

automatic_scaling:
  max_num_instances: 1

resources:
  memory_gb: 6.1

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 300
  timeout_sec: 299

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 300
  timeout_sec: 299
